insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ac', '{"sl":"Ascension Island (Združeno kraljestvo)","en":"Ascension Island (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ae', '{"sl":"Združeni Arabski Emirati","en":"United Arab Emirates"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('af', '{"sl":"Afganistan","en":"Afghanistan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ag', '{"sl":"Antigva in Barbuda","en":"Antigua and Barbuda"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ai', '{"sl":"Anguilla (Združeno kraljestvo)","en":"Anguilla (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('al', '{"sl":"Albanija","en":"Albania"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('am', '{"sl":"Armenija","en":"Armenia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ao', '{"sl":"Angola","en":"Angola"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('aq', '{"sl":"Antarktika","en":"Antarctica"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('as', '{"sl":"Ameriška Samoa (ZDA)","en":"American Samoa (United States)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('au', '{"sl":"Avstralija","en":"Australia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('aw', '{"sl":"Aruba (kraljestvo Nizozemske)","en":"Aruba (Kingdom of the Netherlands)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ax', '{"sl":"Åland (Finska)","en":"Åland (Finland)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bb', '{"sl":"Barbados","en":"Barbados"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bd', '{"sl":"Bangladeš","en":"Bangladesh"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bf', '{"sl":"Burkina Faso","en":"Burkina Faso"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bh', '{"sl":"Bahrajn","en":"Bahrain"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bi', '{"sl":"Burundi","en":"Burundi"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bj', '{"sl":"Benin","en":"Benin"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bm', '{"sl":"Bermuda (Združeno kraljestvo)","en":"Bermuda (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bn', '{"sl":"Brunej","en":"Brunei"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bo', '{"sl":"Bolivija","en":"Bolivia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bq', '{"sl":"Karibska Nizozemska (Bonaire, Saba in Sint Eustatius)","en":"Caribbean Netherlands ( Bonaire,  Saba, and  Sint Eustatius)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('br', '{"sl":"Brazilija","en":"Brazil"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bs', '{"sl":"Bahami","en":"Bahamas"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bt', '{"sl":"Butan","en":"Bhutan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bw', '{"sl":"Bocvana","en":"Botswana"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('bz', '{"sl":"Belize","en":"Belize"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ca', '{"sl":"Kanada","en":"Canada"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cc', '{"sl":"Otoki kokosov (kokosa)","en":"Cocos (Keeling) Islands"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cd', '{"sl":"Demokratična republika Kongo","en":"Democratic Republic of the Congo"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cf', '{"sl":"centralna afriška republika","en":"Central African Republic"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cg', '{"sl":"Republika Kongo","en":"Republic of the Congo"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ci', '{"sl":"Slonokoščena obala","en":"Ivory Coast"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ck', '{"sl":"Kuharski otoki","en":"Cook Islands"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cl', '{"sl":"Čile","en":"Chile"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cm', '{"sl":"Kamerun","en":"Cameroon"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cn', '{"sl":"Ljudska republika Kitajska","en":"Peoples Republic of China"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('co', '{"sl":"Kolumbija","en":"Colombia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cr', '{"sl":"Kostarika","en":"Costa Rica"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cu', '{"sl":"Kuba","en":"Cuba"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cv', '{"sl":"Cape Verde","en":"Cape Verde"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cw', '{"sl":"Curaçao (kraljestvo Nizozemske)","en":"Curaçao (Kingdom of the Netherlands)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('cx', '{"sl":"Božični otok","en":"Christmas Island"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('dj', '{"sl":"Džibuti","en":"Djibouti"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('dm', '{"sl":"Dominica","en":"Dominica"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('do', '{"sl":"Dominikanska republika","en":"Dominican Republic"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('dz', '{"sl":"Alžirija","en":"Algeria"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ec', '{"sl":"Ekvador","en":"Ecuador"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('eg', '{"sl":"Egipt","en":"Egypt"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('eh', '{"sl":"Zahodna Sahara","en":"Western Sahara"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('er', '{"sl":"Eritreja","en":"Eritrea"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('et', '{"sl":"Etiopija","en":"Ethiopia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('eu', '{"sl":"Evropska unija","en":"European Union"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('fj', '{"sl":"Fidži","en":"Fiji"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('fk', '{"sl":"Falklandski otoki (Združeno kraljestvo)","en":"Falkland Islands (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('fm', '{"sl":"Zvezne države mikronezije","en":"Federated States of Micronesia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('fo', '{"sl":"Ferski otoki (kraljestvo Danskega)","en":"Faroe Islands (Kingdom of Denmark)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ga', '{"sl":"Gabon","en":"Gabon"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gd', '{"sl":"GRENADA","en":"Grenada"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gf', '{"sl":"Francoska Gvajana (Francija)","en":"French Guiana (France)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gg', '{"sl":"Guernsey","en":"Guernsey"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gh', '{"sl":"Gana","en":"Ghana"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gi', '{"sl":"Gibraltar (Združeno kraljestvo)","en":"Gibraltar (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gl', '{"sl":"Grenlandija (kraljestvo Danskega)","en":"Greenland (Kingdom of Denmark)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gm', '{"sl":"Gambija","en":"The Gambia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gn', '{"sl":"Gvineja","en":"Guinea"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gp', '{"sl":"Guadelaupe (Francija)","en":"Guadeloupe (France)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gq', '{"sl":"Ekvatorialna Gvineja","en":"Equatorial Guinea"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gs', '{"sl":"Južna Gruzija in južni sendvič otoki (Združeno kraljestvo)","en":"South Georgia and the South Sandwich Islands (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gt', '{"sl":"Gvatemala","en":"Guatemala"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gu', '{"sl":"Guam (ZDA)","en":"Guam (United States)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gw', '{"sl":"Gvineja-Bissau","en":"Guinea-Bissau"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('gy', '{"sl":"Gvajana","en":"Guyana"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('hk', '{"sl":"Hong Kong","en":"Hong Kong"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('hm', '{"sl":"Heard Island in McDonald Islands","en":"Heard Island and McDonald Islands"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('hn', '{"sl":"Honduras","en":"Honduras"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ht', '{"sl":"Haiti","en":"Haiti"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('id', '{"sl":"Indonezija","en":"Indonesia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ie', '{"sl":"Irska","en":"Ireland"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('il', '{"sl":"Izrael","en":"Israel"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('im', '{"sl":"otok Man","en":"Isle of Man"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('in', '{"sl":"Indija","en":"India"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('io', '{"sl":"Ozemlje britanskega Indijskega oceana (Združeno kraljestvo)","en":"British Indian Ocean Territory (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('iq', '{"sl":"Irak","en":"Iraq"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('je', '{"sl":"Jersey","en":"Jersey"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('jm', '{"sl":"Jamajka","en":"Jamaica"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('jo', '{"sl":"Jordan","en":"Jordan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('jp', '{"sl":"Japonska","en":"Japan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ke', '{"sl":"Kenija","en":"Kenya"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('kg', '{"sl":"Kirgizistan","en":"Kyrgyzstan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('kh', '{"sl":"Kambodža","en":"Cambodia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ki', '{"sl":"Kiribati","en":"Kiribati"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('km', '{"sl":"Komoros","en":"Comoros"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('kn', '{"sl":"Saint Kitts in Nevis","en":"Saint Kitts and Nevis"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('kp', '{"sl":"Severna Koreja","en":"North Korea"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('kr', '{"sl":"Južna Koreja","en":"South Korea"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('kw', '{"sl":"Kuvajt","en":"Kuwait"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ky', '{"sl":"Kajmanski otoki (Združeno kraljestvo)","en":"Cayman Islands (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('kz', '{"sl":"Kazahstan","en":"Kazakhstan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('la', '{"sl":"Laos","en":"Laos"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('lb', '{"sl":"Libanon","en":"Lebanon"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('lc', '{"sl":"Sveta Lucia","en":"Saint Lucia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('lk', '{"sl":"Šrilanka","en":"Sri Lanka"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('lr', '{"sl":"Liberija","en":"Liberia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ls', '{"sl":"Lesoto","en":"Lesotho"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('lu', '{"sl":"Luksemburg","en":"Luxembourg"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ly', '{"sl":"Libija","en":"Libya"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ma', '{"sl":"Maroko","en":"Morocco"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mg', '{"sl":"Madagaskar","en":"Madagascar"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mh', '{"sl":"Marshall otoki","en":"Marshall Islands"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ml', '{"sl":"Mali","en":"Mali"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mm', '{"sl":"Mjanmar","en":"Myanmar"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mn', '{"sl":"Mongolija","en":"Mongolia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mo', '{"sl":"Macau","en":"Macau"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mp', '{"sl":"Otoki Severne Mariane (ZDA)","en":"Northern Mariana Islands (United States)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mq', '{"sl":"Martinique (Francija)","en":"Martinique (France)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mr', '{"sl":"Mavretanija","en":"Mauritania"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ms', '{"sl":"Montserrat (Združeno kraljestvo)","en":"Montserrat (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mu', '{"sl":"Mavricij","en":"Mauritius"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mv', '{"sl":"Maldivi","en":"Maldives"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mw', '{"sl":"Malavi","en":"Malawi"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mx', '{"sl":"Mehika","en":"Mexico"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('my', '{"sl":"Malezija","en":"Malaysia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('mz', '{"sl":"Mozambik","en":"Mozambique"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('na', '{"sl":"Namibija","en":"Namibia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('nc', '{"sl":"Nova Kaledonija (Francija)","en":"New Caledonia (France)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ne', '{"sl":"Niger","en":"Niger"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('nf', '{"sl":"Otok Norfolk","en":"Norfolk Island"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ng', '{"sl":"Nigerija","en":"Nigeria"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ni', '{"sl":"Nikaragva","en":"Nicaragua"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('np', '{"sl":"Nepal","en":"Nepal"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('nr', '{"sl":"Nauru","en":"Nauru"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('nu', '{"sl":"Niue","en":"Niue"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('nz', '{"sl":"Nova Zelandija","en":"New Zealand"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('om', '{"sl":"Oman","en":"Oman"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('pa', '{"sl":"Panama","en":"Panama"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('pe', '{"sl":"Peru","en":"Peru"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('pf', '{"sl":"Francoska Polinezija (Francija)","en":"French Polynesia (France)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('pg', '{"sl":"Papua Nova Gvineja","en":"Papua New Guinea"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ph', '{"sl":"Filipini","en":"Philippines"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('pk', '{"sl":"Pakistan","en":"Pakistan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('pm', '{"sl":"Saint-Pierre in Miquelon (Francija)","en":"Saint-Pierre and Miquelon (France)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('pn', '{"sl":"Otoki Pitcairn (Združeno kraljestvo)","en":"Pitcairn Islands (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('pr', '{"sl":"Portoriko (ZDA)","en":"Puerto Rico (United States)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ps', '{"sl":"Palestina [50]","en":"Palestine[50]"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('pw', '{"sl":"Palau","en":"Palau"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('py', '{"sl":"Paragvaj","en":"Paraguay"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('qa', '{"sl":"Katar","en":"Qatar"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('re', '{"sl":"Réunion (Francija)","en":"Réunion (France)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('rw', '{"sl":"Ruanda","en":"Rwanda"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sa', '{"sl":"Savdska Arabija","en":"Saudi Arabia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sb', '{"sl":"Salomonovi otoki","en":"Solomon Islands"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sc', '{"sl":"Sejšeli","en":"Seychelles"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sd', '{"sl":"Sudan","en":"Sudan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sg', '{"sl":"Singapur","en":"Singapore"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sh', '{"sl":"Saint Helena, Ascension in Tristan da Cunha (Združeno kraljestvo)","en":"Saint Helena, Ascension and Tristan da Cunha (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sk', '{"sl":"Slovaška","en":"Slovakia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sn', '{"sl":"Senegal","en":"Senegal"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('so', '{"sl":"Somalija","en":"Somalia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sr', '{"sl":"Suriname","en":"Suriname"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ss', '{"sl":"Južni Sudan","en":"South Sudan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('st', '{"sl":"São Tomé in príncipe","en":"São Tomé and Príncipe"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('su', '{"sl":"Sovjetska zveza","en":"Soviet Union"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sv', '{"sl":"El Salvador","en":"El Salvador"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sx', '{"sl":"Sint Maarten (kraljestvo Nizozemske)","en":"Sint Maarten (Kingdom of the Netherlands)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sy', '{"sl":"Sirija","en":"Syria"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('sz', '{"sl":"Eswatini","en":"Eswatini"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tc', '{"sl":"Otoki Turkov in Caicos (Združeno kraljestvo)","en":"Turks and Caicos Islands (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('td', '{"sl":"Chad","en":"Chad"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tf', '{"sl":"Francoske južne in antarktične dežele","en":"French Southern and Antarctic Lands"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tg', '{"sl":"Iti","en":"Togo"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('th', '{"sl":"Tajska","en":"Thailand"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tj', '{"sl":"Tadžikistan","en":"Tajikistan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tk', '{"sl":"Tokelau","en":"Tokelau"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tl', '{"sl":"Vzhodni Timor","en":"East Timor"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tm', '{"sl":"Turkmenistan","en":"Turkmenistan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tn', '{"sl":"Tunizija","en":"Tunisia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('to', '{"sl":"Tonga","en":"Tonga"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tt', '{"sl":"Trinidad in Tobago","en":"Trinidad and Tobago"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tv', '{"sl":"Tuvalu","en":"Tuvalu"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tw', '{"sl":"Tajvan","en":"Taiwan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('tz', '{"sl":"Tanzanija","en":"Tanzania"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ua', '{"sl":"Ukrajina","en":"Ukraine"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ug', '{"sl":"Uganda","en":"Uganda"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('us', '{"sl":"Združene države Amerike","en":"United States of America"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('uy', '{"sl":"Urugvaj","en":"Uruguay"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('uz', '{"sl":"Uzbekistan","en":"Uzbekistan"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('va', '{"sl":"Vatikan","en":"Vatican City"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('vc', '{"sl":"Saint Vincent in Grenadine","en":"Saint Vincent and the Grenadines"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ve', '{"sl":"Venezuela","en":"Venezuela"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('vg', '{"sl":"Britanski Deviški otoki (Združeno kraljestvo)","en":"British Virgin Islands (United Kingdom)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('vi', '{"sl":"Združene države Deviške otoke (ZDA)","en":"United States Virgin Islands (United States)"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('vn', '{"sl":"Vietnam","en":"Vietnam"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('vu', '{"sl":"Vanuatu","en":"Vanuatu"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('wf', '{"sl":"Wallis in Futuna","en":"Wallis and Futuna"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ws', '{"sl":"Samoa","en":"Samoa"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('ye', '{"sl":"Jemen","en":"Yemen"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('yt', '{"sl":"Maščka","en":"Mayotte"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('za', '{"sl":"Južna Afrika","en":"South Africa"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('zm', '{"sl":"Zambija","en":"Zambia"}', 1, now(), now());
insert into groups (slug, name, group_type_id, created_at, updated_at) values ('zw', '{"sl":"Zimbabve","en":"Zimbabwe"}', 1, now(), now());
