CREATE TABLE bears_biometry_animal_handling (
											  id integer NOT NULL,
											  zivalska_vrsta bigint,
											  nacin_odvzema integer,
											  stevilka_dovoljenja character varying(255),
											  ime_projekta character varying(255),
											  oznaka_telemetrije character varying(255),
											  vzrok_izgube text,
											  vzrok_izgube_pogin text,
											  datum bigint NOT NULL,
											  datum_ocenjen bigint,
											  mesto_odvzema text,
											  mesto_opis text,
											  mesto_podrocje text,
											  mesto_podrocje_2 text,
											  mesto_meka text,
											  hr_broj integer,
											  tip_mesta integer,
											  drugi_tip_mesta text,
											  obmocje_medveda integer,
											  lat double precision,
											  lng double precision,
											  zoom integer,
											  x double precision,
											  y double precision,
											  luo character varying(255),
											  id_lovisca integer,
											  uplenitelj_ime character varying(255),
											  uplenitelj_priimek character varying(255),
											  uplenitelj_adr character varying(255),
											  uplenitelj_tel character varying(255),
											  uplenitelj_drzava smallint,
											  uplenitelj_drzava_drugo character varying(255),
											  spremljevalec_ime character varying(255),
											  spremljevalec_priimek character varying(255),
											  vzorec_vzet integer,
											  vzorec_dlake integer,
											  vzorec_krvi integer,
											  vzorec_zoba integer,
											  vzorec_misica integer,
											  vzorec_osit integer,
											  vzorec_tkivo integer,
											  vzorec_bubreg integer,
											  vzorec_jetra integer,
											  vzorec_pluca integer,
											  vzorec_slezena integer,
											  vzorec_srca integer,
											  loo_tel character varying(255),
											  loo_fax character varying(255),
											  loo_adr character varying(255),
											  loo_email character varying(255),
											  loo_posbroj character varying(255),
											  loo_osoba character varying(255),
											  loo_fun character varying(255),
											  preparator_ime character varying(255),
											  preparator_priimek character varying(255),
											  vnasalec_id bigint,
											  vnasalec_drzava bigint,
											  cas_vnosa bigint NOT NULL,
											  status smallint,
											  identifikacija_osebka character varying(255) DEFAULT NULL::character varying,
											  ime_lovisca character varying(255),
											  gcell public.geometry(Polygon,4326),
											  vzrok_odstranitve text,
											  translocation_location text,
											  stevilka_letnega_odvzema text,
											  date_time date,
											  geom public.geometry(Geometry,4326),
											  licence_id integer DEFAULT 10,
											  CONSTRAINT bears_biometry_animal_handling_cas_vnosa_check CHECK ((cas_vnosa >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_datum_check CHECK ((datum >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_datum_ocenjen_check CHECK ((datum_ocenjen >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_id_check CHECK ((id >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vnasalec_drzava_check CHECK ((vnasalec_drzava >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vnasalec_id_check CHECK ((vnasalec_id >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_bubreg_check CHECK ((vzorec_bubreg >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_dlake_check CHECK ((vzorec_dlake >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_jetra_check CHECK ((vzorec_jetra >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_krvi_check CHECK ((vzorec_krvi >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_misica_check CHECK ((vzorec_misica >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_osit_check CHECK ((vzorec_osit >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_pluca_check CHECK ((vzorec_pluca >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_slezena_check CHECK ((vzorec_slezena >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_srca_check CHECK ((vzorec_srca >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_tkivo_check CHECK ((vzorec_tkivo >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_vzet_check CHECK ((vzorec_vzet >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_vzorec_zoba_check CHECK ((vzorec_zoba >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_zivalska_vrsta_check CHECK ((zivalska_vrsta >= 0)),
											  CONSTRAINT bears_biometry_animal_handling_zoom_check CHECK ((zoom >= 0))
);
