<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('spatial_unit_filter_elements', function (Blueprint $table) {
            $table->id();
			$table->string('slug')->unique();
			$table->string('name');
			$table->unsignedInteger('spatial_unit_filter_type_id');
			$table->foreign('spatial_unit_filter_type_id')
				->references('id')
				->on('spatial_unit_filter_types')
				->onUpdate('cascade')
				->onDelete('cascade');
        });

		DB::table('spatial_unit_filter_elements')->insert([
			[ 'slug' => 'SI-LOV-1018', 'name' => '{"name":"STARŠE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0527', 'name' => '{"name":"Koper"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0513', 'name' => '{"name":"Senožeče"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0906', 'name' => '{"name":"DOBRNA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1404', 'name' => '{"name":"REČICA OB SAVINJI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0401', 'name' => '{"name":"BREZOVICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0715', 'name' => '{"name":"BIZELJSKO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1503', 'name' => '{"name":"DESTRNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0615', 'name' => '{"name":"MISLINJA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1202', 'name' => '{"name":"MOST NA SOČI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0618', 'name' => '{"name":"ZELENI VRH VUZENICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1023', 'name' => '{"name":"LAPORJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1302', 'name' => '{"name":"LAZE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1019', 'name' => '{"name":"RAČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0723', 'name' => '{"name":"VELIKI PODLOG"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0202', 'name' => '{"name":"DOVJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0828', 'name' => '{"name":"BAKOVCI -LIPOVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0304', 'name' => '{"name":"DOBREPOLJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0410', 'name' => '{"name":"CAJNARJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0408', 'name' => '{"name":"RAKEK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0242', 'name' => '{"name":"SOVODENJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0327', 'name' => '{"name":"SMUK SEMIČ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0204', 'name' => '{"name":"BLED"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0917', 'name' => '{"name":"PREBOLD"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0810', 'name' => '{"name":"GRAD - KUZMA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0407', 'name' => '{"name":"RAKOVNIK ŠKOFLJICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0607', 'name' => '{"name":"PREŽIHOVO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1013', 'name' => '{"name":"BENEDIKT"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1401', 'name' => '{"name":"SOLČAVA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0506', 'name' => '{"name":"Brje-Erzelj"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1218', 'name' => '{"name":"VIPAVA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0725', 'name' => '{"name":"KOSTANJEVICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0318', 'name' => '{"name":"OSILNICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0218', 'name' => '{"name":"TRŽIČ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0933', 'name' => '{"name":"PODSREDA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1227', 'name' => '{"name":"PLANINA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0330', 'name' => '{"name":"SUHOR"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1517', 'name' => '{"name":"JOŽE LACKO-PTUJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0518', 'name' => '{"name":"Bukovica"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1204', 'name' => '{"name":"SABOTIN"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0416', 'name' => '{"name":"NOVA VAS"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1223', 'name' => '{"name":"NANOS"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0102', 'name' => '{"name":"VELIKA LOKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1303', 'name' => '{"name":"KRESNICE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1511', 'name' => '{"name":"BRESNICA-PODGORCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1410', 'name' => '{"name":"BRASLOVČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1228', 'name' => '{"name":"LOGATEC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0511', 'name' => '{"name":"Tabor Sežana"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0421', 'name' => '{"name":"IGA VAS"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1312', 'name' => '{"name":"HRASTNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1524', 'name' => '{"name":"MAKOLE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1212', 'name' => '{"name":"ČAVEN"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1409', 'name' => '{"name":"DRETA NAZARJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1519', 'name' => '{"name":"PTUJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1005', 'name' => '{"name":"KOŠAKI-MALEČNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0507', 'name' => '{"name":"Štanjel"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0209', 'name' => '{"name":"STARA FUŽINA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1201', 'name' => '{"name":"KANAL"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0803', 'name' => '{"name":"NEGOVA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1514', 'name' => '{"name":"ZAVRČ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0703', 'name' => '{"name":"SEVNICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0525', 'name' => '{"name":"Marezige"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0239', 'name' => '{"name":"POLJANE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1516', 'name' => '{"name":"MARKOVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0915', 'name' => '{"name":"HUM CELJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0217', 'name' => '{"name":"UDENBORŠT"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1510', 'name' => '{"name":"VELIKA NEDELJA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1203', 'name' => '{"name":"DOBROVO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1211', 'name' => '{"name":"TRNOVSKI GOZD"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0528', 'name' => '{"name":"Šmarje"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1002', 'name' => '{"name":"ŠENTILJ V SLOVENSKIH GORICAH"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0630', 'name' => '{"name":"RUŠE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1108', 'name' => '{"name":"SMAST"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1012', 'name' => '{"name":"LENART V SLOVENSKIH GORICAH"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0816', 'name' => '{"name":"RANKOVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0711', 'name' => '{"name":"KRŠKO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0601', 'name' => '{"name":"KOPRIVNA TOPLA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1411', 'name' => '{"name":"VRANSKO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0901', 'name' => '{"name":"ŠKALE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0113', 'name' => '{"name":"TRŽIŠČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0808', 'name' => '{"name":"LJUTOMER"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0832', 'name' => '{"name":"PETIŠOVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0823', 'name' => '{"name":"MLAJTINCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1007', 'name' => '{"name":"JAKOB"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1308', 'name' => '{"name":"ČEMŠENIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0621', 'name' => '{"name":"ORLICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0427', 'name' => '{"name":"ZEMON"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0114', 'name' => '{"name":"OTOČEC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1016', 'name' => '{"name":"DUPLEK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0805', 'name' => '{"name":"VIDEM OB ŠČAVNICI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0815', 'name' => '{"name":"KRIŽEVCI V PREKMURJU"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0240', 'name' => '{"name":"GORENJA VAS"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1320', 'name' => '{"name":"POLŠNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1506', 'name' => '{"name":"IVANJKOVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0420', 'name' => '{"name":"LOŽ - STARI TRG"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0829', 'name' => '{"name":"LPN FAZAN-BELTINCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0505', 'name' => '{"name":"Dolce-Komen"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1507', 'name' => '{"name":"KOG-VINSKI VRHOVI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0504', 'name' => '{"name":"Jezero-Komen"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1521', 'name' => '{"name":"PODLEHNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0320', 'name' => '{"name":"PREDGRAD"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0523', 'name' => '{"name":"Rižana"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0517', 'name' => '{"name":"Prem"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0206', 'name' => '{"name":"BEGUNJŠČICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1017', 'name' => '{"name":"POBREŽJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0412', 'name' => '{"name":"MOKRC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0302', 'name' => '{"name":"TABORSKA JAMA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1104', 'name' => '{"name":"SOČA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0918', 'name' => '{"name":"TABOR"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0613', 'name' => '{"name":"GRADIŠČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0305', 'name' => '{"name":"SUHA KRAJINA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0115', 'name' => '{"name":"ŠKOCJAN"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0920', 'name' => '{"name":"LAŠKO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0119', 'name' => '{"name":"BRUSNICE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0909', 'name' => '{"name":"SLOVENSKE KONJICE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0229', 'name' => '{"name":"ŠMARNA GORA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0417', 'name' => '{"name":"PRESTRANEK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0502', 'name' => '{"name":"Trstelj-Kostanjevica"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1405', 'name' => '{"name":"MOZIRJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0307', 'name' => '{"name":"VELIKE LAŠČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0121', 'name' => '{"name":"ŠENTJERNEJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1107', 'name' => '{"name":"KOBARID"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0214', 'name' => '{"name":"SELCA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0716', 'name' => '{"name":"GLOBOKO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0108', 'name' => '{"name":"ŠENTJANŽ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0508', 'name' => '{"name":"Kras-Dutovlje"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0230', 'name' => '{"name":"TOŠKO ČELO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1307', 'name' => '{"name":"IZLAKE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1508', 'name' => '{"name":"SREDIŠČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0710', 'name' => '{"name":"RAKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0203', 'name' => '{"name":"JESENICE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0625', 'name' => '{"name":"KAPLA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0824', 'name' => '{"name":"MORAVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0411', 'name' => '{"name":"ŽILCE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0708', 'name' => '{"name":"SENOVO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0632', 'name' => '{"name":"HOČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0610', 'name' => '{"name":"LIBELIČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0233', 'name' => '{"name":"POLHOV GRADEC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0212', 'name' => '{"name":"SORICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1106', 'name' => '{"name":"DREŽNICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1205', 'name' => '{"name":"ANHOVO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0821', 'name' => '{"name":"TIŠINA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0719', 'name' => '{"name":"DOBOVA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0332', 'name' => '{"name":"LPN MEDVED KOČEVJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1413', 'name' => '{"name":"KAMNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0333', 'name' => '{"name":"LPN ŽITNA GORA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1020', 'name' => '{"name":"POLSKAVA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1206', 'name' => '{"name":"GRGAR"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1110', 'name' => '{"name":"VOLČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0222', 'name' => '{"name":"JEZERSKO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0809', 'name' => '{"name":"ROGAŠOVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1304', 'name' => '{"name":"MORAVČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0826', 'name' => '{"name":"DOBROVNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0614', 'name' => '{"name":"GOLAVABUKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0227', 'name' => '{"name":"MENGEŠ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0919', 'name' => '{"name":"REČICA PRI LAŠKEM"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0213', 'name' => '{"name":"ŽELEZNIKI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0110', 'name' => '{"name":"MIRNA PEČ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0331', 'name' => '{"name":"LPN SNEŽNIK KOČEVSKA REKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0520', 'name' => '{"name":"Žabnik-Obrov"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0605', 'name' => '{"name":"PODGORJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1221', 'name' => '{"name":"DOLE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0221', 'name' => '{"name":"LPN KOZOROG KAMNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0314', 'name' => '{"name":"KOČEVJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0312', 'name' => '{"name":"DOLENJA VAS"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0637', 'name' => '{"name":"ZREČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1111', 'name' => '{"name":"LPN PRODI - RAZOR"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0603', 'name' => '{"name":"PECA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0104', 'name' => '{"name":"DOBRNIČ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0802', 'name' => '{"name":"GORNJA RADGONA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0617', 'name' => '{"name":"LPN POHORJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1526', 'name' => '{"name":"ŽETALE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1408', 'name' => '{"name":"GORNJI GRAD"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0109', 'name' => '{"name":"NOVO MESTO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1403', 'name' => '{"name":"LJUBNO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0819', 'name' => '{"name":"IVANOVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0722', 'name' => '{"name":"CERKLJE OB KRKI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1501', 'name' => '{"name":"TRNOVSKA VAS"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0403', 'name' => '{"name":"BOROVNICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0811', 'name' => '{"name":"LPNKOMPAS - PESKOVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0215', 'name' => '{"name":"JOŠT - KRANJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0516', 'name' => '{"name":"Gradišče-Košana"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1217', 'name' => '{"name":"JELENK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0207', 'name' => '{"name":"JELOVICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0422', 'name' => '{"name":"BABNO POLJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1527', 'name' => '{"name":"ROGATEC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0927', 'name' => '{"name":"HANDIL-DOBJE PRI PLANINI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1113', 'name' => '{"name":"PODBRDO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1214', 'name' => '{"name":"KOZJE STENA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1103', 'name' => '{"name":"BOVEC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0425', 'name' => '{"name":"TRNOVO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0509', 'name' => '{"name":"Vrhe-Vrabče"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0926', 'name' => '{"name":"LOKA PRI ŽUSMU"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0712', 'name' => '{"name":"VIDEM OB SAVI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0503', 'name' => '{"name":"Tabor-Dornberk"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1101', 'name' => '{"name":"LPN TRIGLAV"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0611', 'name' => '{"name":"DRAVOGRAD"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0426', 'name' => '{"name":"KOZLEK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0236', 'name' => '{"name":"SORŠKO POLJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0705', 'name' => '{"name":"BUČKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0619', 'name' => '{"name":"MUTA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0404', 'name' => '{"name":"RAKITNA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0514', 'name' => '{"name":"Videž-Kozina"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0524', 'name' => '{"name":"Istra-Gračišče"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0237', 'name' => '{"name":"KRIŽNA GORA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1210', 'name' => '{"name":"LIJAK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0813', 'name' => '{"name":"RADOVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0308', 'name' => '{"name":"VELIKE POLJANE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0116', 'name' => '{"name":"TOPLICE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0419', 'name' => '{"name":"GORNJE JEZERO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0519', 'name' => '{"name":"Brkini"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0620', 'name' => '{"name":"RADLJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0234', 'name' => '{"name":"HORJUL"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0717', 'name' => '{"name":"KAPELE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1209', 'name' => '{"name":"GORICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0904', 'name' => '{"name":"POLZELA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0405', 'name' => '{"name":"TOMIŠELJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0629', 'name' => '{"name":"GAJ NAD MARIBOROM"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0406', 'name' => '{"name":"IG"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1010', 'name' => '{"name":"SV. JURIJ-JUROVSKI DOL"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1004', 'name' => '{"name":"KAMNICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0208', 'name' => '{"name":"KROPA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0907', 'name' => '{"name":"VITANJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1505', 'name' => '{"name":"TOMAŽ PRI ORMOŽU"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1105', 'name' => '{"name":"ČEZSOČA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1418', 'name' => '{"name":"LUKOVICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1309', 'name' => '{"name":"ŠENTLAMBERT"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0902', 'name' => '{"name":"OLJKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0631', 'name' => '{"name":"RADVANJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1315', 'name' => '{"name":"VIŠNJA GORA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1406', 'name' => '{"name":"SMREKOVEC ŠOŠTANJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0319', 'name' => '{"name":"BANJA LOKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0111', 'name' => '{"name":"TREBELNO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0914', 'name' => '{"name":"GRMADA CELJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1416', 'name' => '{"name":"MOTNIK ŠPITALIČ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0225', 'name' => '{"name":"KOMENDA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0107', 'name' => '{"name":"ŠENTRUPERT"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0323', 'name' => '{"name":"VINICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0924', 'name' => '{"name":"ŠMARJE PRI JELŠAH"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0241', 'name' => '{"name":"ŽIRI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1014', 'name' => '{"name":"DOBRAVA V SLOVENSKIH GORICAH"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0510', 'name' => '{"name":"Raša-Štorje"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0903', 'name' => '{"name":"VELENJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1414', 'name' => '{"name":"SELA PRI KAMNIKU"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1009', 'name' => '{"name":"SV. ANA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1216', 'name' => '{"name":"IDRIJA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0812', 'name' => '{"name":"CANKOVA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0313', 'name' => '{"name":"STRUGE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0827', 'name' => '{"name":"KOBILJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0928', 'name' => '{"name":"JURKLOŠTER"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0413', 'name' => '{"name":"JAVORNIK POSTOJNA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0526', 'name' => '{"name":"Dekani"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0309', 'name' => '{"name":"SODRAŽICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1311', 'name' => '{"name":"TRBOVLJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0235', 'name' => '{"name":"ŠENTJOŠT"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0205', 'name' => '{"name":"STOL ŽIROVNICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0905', 'name' => '{"name":"ŽALEC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1224', 'name' => '{"name":"HRENOVICE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0210', 'name' => '{"name":"BOHINJSKA BISTRICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0634', 'name' => '{"name":"ŠMARTNO NA POHORJU"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0831', 'name' => '{"name":"LENDAVA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1314', 'name' => '{"name":"DOL PRI HRASTNIKU"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0211', 'name' => '{"name":"NOMENJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0201', 'name' => '{"name":"KRANJSKA GORA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1502', 'name' => '{"name":"VITOMARCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0609', 'name' => '{"name":"STROJNA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0415', 'name' => '{"name":"GRAHOVO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0112', 'name' => '{"name":"MOKRONOG"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1231', 'name' => '{"name":"VRHNIKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1015', 'name' => '{"name":"VOLIČINA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1321', 'name' => '{"name":"GABROVKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0807', 'name' => '{"name":"MALA NEDELJA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0929', 'name' => '{"name":"BOHOR-PL. PRI SEVNICI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0825', 'name' => '{"name":"BOGOJINA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1116', 'name' => '{"name":"POREZEN"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1022', 'name' => '{"name":"CIGONCA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1112', 'name' => '{"name":"LJUBINJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1011', 'name' => '{"name":"PERNICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0911', 'name' => '{"name":"PONIKVA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0315', 'name' => '{"name":"MALA GORA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0321', 'name' => '{"name":"SINJI VRH"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0922', 'name' => '{"name":"ŠENTJUR"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0529', 'name' => '{"name":"Izola"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0721', 'name' => '{"name":"ČATEŽ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0612', 'name' => '{"name":"BUKOVJE - OTIŠKI VRH"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1306', 'name' => '{"name":"MLINŠE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0633', 'name' => '{"name":"FRAM"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1529', 'name' => '{"name":"POLJČANE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1313', 'name' => '{"name":"DOBOVEC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1219', 'name' => '{"name":"COL"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1518', 'name' => '{"name":"BORIS KIDRIČ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0409', 'name' => '{"name":"BEGUNJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0706', 'name' => '{"name":"STUDENEC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0714', 'name' => '{"name":"PIŠECE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0602', 'name' => '{"name":"BISTRA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0105', 'name' => '{"name":"TREBNJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0709', 'name' => '{"name":"VELIKI KAMEN"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1528', 'name' => '{"name":"ROGAŠKA SLATINA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1220', 'name' => '{"name":"JAVORNIK ČRNI VRH"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0627', 'name' => '{"name":"VURMAT"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0329', 'name' => '{"name":"METLIKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0316', 'name' => '{"name":"LAZINA HINJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0118', 'name' => '{"name":"GORJANCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1006', 'name' => '{"name":"PESNICA - JARENINA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1222', 'name' => '{"name":"VOJKOVO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0220', 'name' => '{"name":"LPN BRDO PRI KRANJU"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0120', 'name' => '{"name":"OREHOVICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1114', 'name' => '{"name":"PLANOTA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0402', 'name' => '{"name":"LPNLJUBLJANSKI VRH"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0322', 'name' => '{"name":"DRAGATUŠ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1109', 'name' => '{"name":"TOLMIN"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1208', 'name' => '{"name":"TREBUŠA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1515', 'name' => '{"name":"CIRKULANE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1316', 'name' => '{"name":"IVANČNA GORICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0817', 'name' => '{"name":"BREZOVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0635', 'name' => '{"name":"SL. BISTRICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0216', 'name' => '{"name":"DOBRČA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0912', 'name' => '{"name":"DRAMLJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1419', 'name' => '{"name":"TROJANE OŽBOLT"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1415', 'name' => '{"name":"TUHINJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0324', 'name' => '{"name":"LOKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0701', 'name' => '{"name":"LOKA PRI ZIDANEM MOSTU"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1512', 'name' => '{"name":"DORNAVA-POLENŠAK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1102', 'name' => '{"name":"LOG POD MANGRTOM"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0622', 'name' => '{"name":"JANŽEV VRH"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1230', 'name' => '{"name":"ROVTE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0325', 'name' => '{"name":"ADLEŠIČI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1301', 'name' => '{"name":"PUGLED"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0423', 'name' => '{"name":"LPN JELEN SNEŽNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0830', 'name' => '{"name":"VELIKA POLANA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0932', 'name' => '{"name":"BISTRICA OB SOTLI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0224', 'name' => '{"name":"KRVAVEC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0628', 'name' => '{"name":"BOČ NA KOZJAKU"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0232', 'name' => '{"name":"DOBROVA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0930', 'name' => '{"name":"KOZJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0521', 'name' => '{"name":"Slavnik-Materija"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1530', 'name' => '{"name":"BOČ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1509', 'name' => '{"name":"ORMOŽ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0910', 'name' => '{"name":"LOČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1525', 'name' => '{"name":"STOPERCE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1229', 'name' => '{"name":"HOTEDRŠICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0106', 'name' => '{"name":"MIRNA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0804', 'name' => '{"name":"RADENCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1323', 'name' => '{"name":"PODKUM"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0724', 'name' => '{"name":"PODBOČJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0303', 'name' => '{"name":"KRKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0219', 'name' => '{"name":"STORŽIČ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0606', 'name' => '{"name":"SLOVENJ GRADEC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0238', 'name' => '{"name":"ŠKOFJA LOKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0626', 'name' => '{"name":"PUŠČAVA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1407', 'name' => '{"name":"VELUNJA ŠOŠTANJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0616', 'name' => '{"name":"DOLIČ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1310', 'name' => '{"name":"ZAGORJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0512', 'name' => '{"name":"Gaberk-Divača"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0623', 'name' => '{"name":"REMŠNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0636', 'name' => '{"name":"OPLOTNICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0326', 'name' => '{"name":"ČRNOMELJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0103', 'name' => '{"name":"PLEŠIVICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0916', 'name' => '{"name":"GOZDNIK GRIŽE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1226', 'name' => '{"name":"BUKOVJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0720', 'name' => '{"name":"MOKRICE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0931', 'name' => '{"name":"PODČETRTEK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0814', 'name' => '{"name":"PEČAROVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0515', 'name' => '{"name":"Timav-Vreme"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0310', 'name' => '{"name":"LOŠKI POTOK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1215', 'name' => '{"name":"KREKOVŠE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0704', 'name' => '{"name":"ZABUKOVJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1001', 'name' => '{"name":"KUNGOTA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0231', 'name' => '{"name":"MEDVODE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1305', 'name' => '{"name":"VAČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0806', 'name' => '{"name":"KRIŽEVCI PRI LJUTOMERU"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0101', 'name' => '{"name":"VELIKI GABER"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0801', 'name' => '{"name":"APAČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1115', 'name' => '{"name":"OTAVNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1207', 'name' => '{"name":"ČEPOVAN"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0820', 'name' => '{"name":"PROSENJAKOVCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0223', 'name' => '{"name":"ŠENČUR"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0301', 'name' => '{"name":"GROSUPLJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0604', 'name' => '{"name":"POGOREVC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1003', 'name' => '{"name":"PALOMA-SLADKI VRH"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0822', 'name' => '{"name":"MURSKA SOBOTA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0713', 'name' => '{"name":"ARTIČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0530', 'name' => '{"name":"Strunjan"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0117', 'name' => '{"name":"PADEŽ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1520', 'name' => '{"name":"LESKOVEC V HALOZAH"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0818', 'name' => '{"name":"DOLINA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1402', 'name' => '{"name":"LUČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0923', 'name' => '{"name":"LOG ŠENTVID"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1021', 'name' => '{"name":"ČREŠNJEVEC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1324', 'name' => '{"name":"RADEČE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1522', 'name' => '{"name":"DRAVINJA - MAJŠPERK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1318', 'name' => '{"name":"ŠMARTNO PRI LITIJI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0228', 'name' => '{"name":"PŠATA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0522', 'name' => '{"name":"Kojnik-Podgorje"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1513', 'name' => '{"name":"SV. MARJETA NIŽE PTUJA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0608', 'name' => '{"name":"JAMNICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1322', 'name' => '{"name":"DOLE PRI LITIJI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1412', 'name' => '{"name":"STAHOVICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0925', 'name' => '{"name":"PRISTAVA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0702', 'name' => '{"name":"BOŠTANJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1008', 'name' => '{"name":"VELKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0418', 'name' => '{"name":"PIVKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0306', 'name' => '{"name":"TURJAK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1213', 'name' => '{"name":"HUBELJ"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0921', 'name' => '{"name":"BOJANSKO ŠTORE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0624', 'name' => '{"name":"PODVELKA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1225', 'name' => '{"name":"ČRNA JAMA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0913', 'name' => '{"name":"KAJUH ŠMARTNO"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1317', 'name' => '{"name":"ŠENTVID PRI STIČNI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0424', 'name' => '{"name":"TABOR ZAGORJE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0501', 'name' => '{"name":"Fajti hrib"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0226', 'name' => '{"name":"VODICE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1504', 'name' => '{"name":"JURŠINCI"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0328', 'name' => '{"name":"GRADAC"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1417', 'name' => '{"name":"DOMŽALE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1319', 'name' => '{"name":"LITIJA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0718', 'name' => '{"name":"BREŽICE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0317', 'name' => '{"name":"DRAGA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-1523', 'name' => '{"name":"CIRKOVCE"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0908', 'name' => '{"name":"VOJNIK"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0414', 'name' => '{"name":"CERKNICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0311', 'name' => '{"name":"RIBNICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LOV-0707', 'name' => '{"name":"BRESTANICA"}', 'spatial_unit_filter_type_id' => 1 ],
			[ 'slug' => 'SI-LUO-11', 'name' => '{"name":"Triglavsko"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-6', 'name' => '{"name":"Pohorsko"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-7', 'name' => '{"name":"Posavsko"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-3', 'name' => '{"name":"Kočevsko Belokranjsko"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-9', 'name' => '{"name":"Savinjsko Kozjansko"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-1', 'name' => '{"name":"Novomeško"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-12', 'name' => '{"name":"Zahodno visoko Kraško"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-14', 'name' => '{"name":"Kamniško Savinjsko"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-4', 'name' => '{"name":"Notranjsko"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-2', 'name' => '{"name":"Gorenjsko"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-5', 'name' => '{"name":"Primorsko"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-8', 'name' => '{"name":"Pomursko"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-10', 'name' => '{"name":"Slovensko goriško"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-15', 'name' => '{"name":"Ptujsko Ormoško"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-LUO-13', 'name' => '{"name":"Zasavsko"}', 'spatial_unit_filter_type_id' => 2 ],
			[ 'slug' => 'SI-OB-111', 'name' => '{"name":"Sežana","mid":"11027377","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-100', 'name' => '{"name":"Radenci","mid":"11027253","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-101', 'name' => '{"name":"Radlje ob Dravi","mid":"11027261","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-5', 'name' => '{"name":"Borovnica","mid":"11026567","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-12', 'name' => '{"name":"Cerklje na Gorenjskem","mid":"11026630","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-202', 'name' => '{"name":"Središče ob Dravi","mid":"21433632","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-167', 'name' => '{"name":"Lovrenc na Pohorju","mid":"21427845","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-112', 'name' => '{"name":"Slovenj Gradec","mid":"11027385","type":"D"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-153', 'name' => '{"name":"Cerkvenjak","mid":"21427683","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-179', 'name' => '{"name":"Sodražica","mid":"21428060","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-26', 'name' => '{"name":"Duplek","mid":"11026796","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-84', 'name' => '{"name":"Nova Gorica","mid":"11027156","type":"D"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-11', 'name' => '{"name":"Celje","mid":"11026621","type":"D"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-123', 'name' => '{"name":"Škofljica","mid":"11027504","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-197', 'name' => '{"name":"Kostanjevica na Krki","mid":"21436453","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-81', 'name' => '{"name":"Muta","mid":"11027938","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-66', 'name' => '{"name":"Loški Potok","mid":"11027067","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-205', 'name' => '{"name":"Sveti Tomaž","mid":"21433675","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-146', 'name' => '{"name":"Železniki","mid":"11028128","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-162', 'name' => '{"name":"Horjul","mid":"21427772","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-105', 'name' => '{"name":"Rogašovci","mid":"11027318","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-39', 'name' => '{"name":"Ivančna Gorica","mid":"11026915","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-98', 'name' => '{"name":"Rače-Fram","mid":"11027245","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-156', 'name' => '{"name":"Dobrovnik","mid":"21427713","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-158', 'name' => '{"name":"Grad","mid":"21427730","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-151', 'name' => '{"name":"Braslovče","mid":"21427667","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-62', 'name' => '{"name":"Ljubno","mid":"11027032","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-178', 'name' => '{"name":"Selnica ob Dravi","mid":"21427900","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-67', 'name' => '{"name":"Luče","mid":"11027075","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-43', 'name' => '{"name":"Kamnik","mid":"11027733","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-131', 'name' => '{"name":"Tržič","mid":"11027598","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-177', 'name' => '{"name":"Ribnica na Pohorju","mid":"21428051","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-71', 'name' => '{"name":"Medvode","mid":"11027890","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-114', 'name' => '{"name":"Slovenske Konjice","mid":"11027407","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-32', 'name' => '{"name":"Grosuplje","mid":"11026869","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-212', 'name' => '{"name":"Mirna","mid":"24063518","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-139', 'name' => '{"name":"Vojnik","mid":"11028080","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-13', 'name' => '{"name":"Cerknica","mid":"11026648","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-78', 'name' => '{"name":"Moravske Toplice","mid":"11027130","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-138', 'name' => '{"name":"Vodice","mid":"11027644","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-170', 'name' => '{"name":"Mirna Peč","mid":"21427853","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-45', 'name' => '{"name":"Kidričevo","mid":"11027741","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-106', 'name' => '{"name":"Rogaška Slatina","mid":"11027326","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-75', 'name' => '{"name":"Miren-Kostanjevica","mid":"11027911","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-47', 'name' => '{"name":"Kobilje","mid":"11027750","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-14', 'name' => '{"name":"Cerkno","mid":"11026656","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-206', 'name' => '{"name":"Šmarješke Toplice","mid":"21433683","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-44', 'name' => '{"name":"Kanal","mid":"11026940","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-95', 'name' => '{"name":"Preddvor","mid":"11027237","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-15', 'name' => '{"name":"Črenšovci","mid":"11026664","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-72', 'name' => '{"name":"Mengeš","mid":"11027091","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-148', 'name' => '{"name":"Benedikt","mid":"21427624","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-135', 'name' => '{"name":"Videm","mid":"11028063","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-96', 'name' => '{"name":"Ptuj","mid":"11028039","type":"D"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-51', 'name' => '{"name":"Kozje","mid":"11026974","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-124', 'name' => '{"name":"Šmarje pri Jelšah","mid":"11027512","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-91', 'name' => '{"name":"Pivka","mid":"11028004","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-57', 'name' => '{"name":"Laško","mid":"11027814","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-89', 'name' => '{"name":"Pesnica","mid":"11027199","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-17', 'name' => '{"name":"Črnomelj","mid":"11026699","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-8', 'name' => '{"name":"Brezovica","mid":"11026591","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-28', 'name' => '{"name":"Gorišnica","mid":"11026818","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-142', 'name' => '{"name":"Zagorje ob Savi","mid":"11027679","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-163', 'name' => '{"name":"Jezersko","mid":"21427799","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-196', 'name' => '{"name":"Cirkulane","mid":"21436445","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-143', 'name' => '{"name":"Zavrč","mid":"11028101","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-172', 'name' => '{"name":"Podlehnik","mid":"21427870","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-160', 'name' => '{"name":"Hoče-Slivnica","mid":"21427756","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-211', 'name' => '{"name":"Šentrupert","mid":"24063500","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-99', 'name' => '{"name":"Radeče","mid":"11028055","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-64', 'name' => '{"name":"Logatec","mid":"11027059","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-83', 'name' => '{"name":"Nazarje","mid":"11027954","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-80', 'name' => '{"name":"Murska Sobota","mid":"11027148","type":"D"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-210', 'name' => '{"name":"Sveti Jurij v Slovenskih goricah","mid":"24063496","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-129', 'name' => '{"name":"Trbovlje","mid":"11027571","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-125', 'name' => '{"name":"Šmartno ob Paki","mid":"11027539","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-174', 'name' => '{"name":"Prebold","mid":"21427888","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-50', 'name' => '{"name":"Koper","mid":"11027776","type":"D"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-76', 'name' => '{"name":"Mislinja","mid":"11027113","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-27', 'name' => '{"name":"Gorenja vas-Poljane","mid":"11026800","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-59', 'name' => '{"name":"Lendava","mid":"11027822","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-10', 'name' => '{"name":"Tišina","mid":"11026613","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-122', 'name' => '{"name":"Škofja Loka","mid":"11027482","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-157', 'name' => '{"name":"Dolenjske Toplice","mid":"21427721","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-70', 'name' => '{"name":"Maribor","mid":"11027881","type":"D"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-2', 'name' => '{"name":"Beltinci","mid":"11026524","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-149', 'name' => '{"name":"Bistrica ob Sotli","mid":"21427632","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-60', 'name' => '{"name":"Litija","mid":"11027024","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-127', 'name' => '{"name":"Štore","mid":"11027555","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-133', 'name' => '{"name":"Velenje","mid":"11027610","type":"D"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-38', 'name' => '{"name":"Ilirska Bistrica","mid":"11027717","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-128', 'name' => '{"name":"Tolmin","mid":"11027563","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-140', 'name' => '{"name":"Vrhnika","mid":"11027652","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-42', 'name' => '{"name":"Juršinci","mid":"11026931","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-74', 'name' => '{"name":"Mežica","mid":"11027105","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-97', 'name' => '{"name":"Puconci","mid":"11028047","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-63', 'name' => '{"name":"Ljutomer","mid":"11027857","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-183', 'name' => '{"name":"Šempeter-Vrtojba","mid":"21427926","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-40', 'name' => '{"name":"Izola","mid":"11026923","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-61', 'name' => '{"name":"Ljubljana","mid":"11027849","type":"D"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-165', 'name' => '{"name":"Kostel","mid":"21427829","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-150', 'name' => '{"name":"Bloke","mid":"21427659","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-36', 'name' => '{"name":"Idrija","mid":"11026893","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-207', 'name' => '{"name":"Gorje","mid":"24063461","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-41', 'name' => '{"name":"Jesenice","mid":"11027725","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-181', 'name' => '{"name":"Sveta Ana","mid":"21428078","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-9', 'name' => '{"name":"Brežice","mid":"11026605","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-93', 'name' => '{"name":"Podvelka","mid":"11028012","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-182', 'name' => '{"name":"Sveti Andraž v Slov. goricah","mid":"21428086","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-55', 'name' => '{"name":"Kungota","mid":"11027008","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-201', 'name' => '{"name":"Renče-Vogrsko","mid":"24063453","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-102', 'name' => '{"name":"Radovljica","mid":"11027270","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-31', 'name' => '{"name":"Gornji Petrovci","mid":"11026842","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-200', 'name' => '{"name":"Poljčane","mid":"21436488","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-48', 'name' => '{"name":"Kočevje","mid":"11026966","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-130', 'name' => '{"name":"Trebnje","mid":"11027580","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-94', 'name' => '{"name":"Postojna","mid":"11027229","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-121', 'name' => '{"name":"Škocjan","mid":"11027474","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-73', 'name' => '{"name":"Metlika","mid":"11027903","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-141', 'name' => '{"name":"Vuzenica","mid":"11028098","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-152', 'name' => '{"name":"Cankova","mid":"21427675","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-137', 'name' => '{"name":"Vitanje","mid":"11028071","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-3', 'name' => '{"name":"Bled","mid":"11026532","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-168', 'name' => '{"name":"Markovci","mid":"21428019","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-175', 'name' => '{"name":"Prevalje","mid":"21428043","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-132', 'name' => '{"name":"Turnišče","mid":"11027601","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-49', 'name' => '{"name":"Komen","mid":"11027768","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-58', 'name' => '{"name":"Lenart","mid":"11027016","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-24', 'name' => '{"name":"Dornava","mid":"11026770","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-199', 'name' => '{"name":"Mokronog-Trebelno","mid":"21436470","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-37', 'name' => '{"name":"Ig","mid":"11026907","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-82', 'name' => '{"name":"Naklo","mid":"11027946","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-109', 'name' => '{"name":"Semič","mid":"11027342","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-52', 'name' => '{"name":"Kranj","mid":"11027784","type":"D"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-186', 'name' => '{"name":"Trzin","mid":"21427969","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-77', 'name' => '{"name":"Moravče","mid":"11027121","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-190', 'name' => '{"name":"Žalec","mid":"21428124","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-187', 'name' => '{"name":"Velika Polana","mid":"21428094","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-147', 'name' => '{"name":"Žiri","mid":"11027695","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-116', 'name' => '{"name":"Sveti Jurij ob Ščavnici","mid":"11027423","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-204', 'name' => '{"name":"Sveta Trojica v Slovenskih goricah","mid":"21433667","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-164', 'name' => '{"name":"Komenda","mid":"21427802","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-34', 'name' => '{"name":"Hrastnik","mid":"11026885","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-23', 'name' => '{"name":"Domžale","mid":"11026761","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-4', 'name' => '{"name":"Bohinj","mid":"11026559","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-79', 'name' => '{"name":"Mozirje","mid":"11027920","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-69', 'name' => '{"name":"Majšperk","mid":"11027083","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-188', 'name' => '{"name":"Veržej","mid":"21427977","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-189', 'name' => '{"name":"Vransko","mid":"21428108","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-7', 'name' => '{"name":"Brda","mid":"11026583","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-1', 'name' => '{"name":"Ajdovščina","mid":"11026516","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-46', 'name' => '{"name":"Kobarid","mid":"11026958","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-85', 'name' => '{"name":"Novo mesto","mid":"11027962","type":"D"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-107', 'name' => '{"name":"Rogatec","mid":"11027300","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-134', 'name' => '{"name":"Velike Lašče","mid":"11027628","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-53', 'name' => '{"name":"Kranjska Gora","mid":"11027792","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-88', 'name' => '{"name":"Osilnica","mid":"11027989","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-176', 'name' => '{"name":"Razkrižje","mid":"21427896","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-90', 'name' => '{"name":"Piran","mid":"11027997","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-113', 'name' => '{"name":"Slovenska Bistrica","mid":"11027393","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-193', 'name' => '{"name":"Žužemberk","mid":"21427993","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-30', 'name' => '{"name":"Gornji Grad","mid":"11026834","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-20', 'name' => '{"name":"Dobrepolje","mid":"11026737","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-103', 'name' => '{"name":"Ravne na Koroškem","mid":"11027288","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-68', 'name' => '{"name":"Lukovica","mid":"11027873","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-166', 'name' => '{"name":"Križevci","mid":"21427837","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-136', 'name' => '{"name":"Vipava","mid":"11027636","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-194', 'name' => '{"name":"Šmartno pri Litiji","mid":"21428264","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-115', 'name' => '{"name":"Starše","mid":"11027415","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-117', 'name' => '{"name":"Šenčur","mid":"11027431","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-192', 'name' => '{"name":"Žirovnica","mid":"21428116","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-209', 'name' => '{"name":"Rečica ob Savinji","mid":"24063488","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-171', 'name' => '{"name":"Oplotnica","mid":"21427861","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-185', 'name' => '{"name":"Trnovska vas","mid":"21427942","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-191', 'name' => '{"name":"Žetale","mid":"21427985","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-86', 'name' => '{"name":"Odranci","mid":"11027164","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-33', 'name' => '{"name":"Šalovci","mid":"11026877","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-54', 'name' => '{"name":"Krško","mid":"11026982","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-6', 'name' => '{"name":"Bovec","mid":"11026575","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-155', 'name' => '{"name":"Dobrna","mid":"21427705","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-21', 'name' => '{"name":"Dobrova-Polhov Gradec","mid":"11026745","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-56', 'name' => '{"name":"Kuzma","mid":"11027806","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-198', 'name' => '{"name":"Makole","mid":"21436461","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-184', 'name' => '{"name":"Tabor","mid":"21427934","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-104', 'name' => '{"name":"Ribnica","mid":"11027296","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-16', 'name' => '{"name":"Črna na Koroškem","mid":"11026672","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-65', 'name' => '{"name":"Loška dolina","mid":"11027865","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-161', 'name' => '{"name":"Hodoš","mid":"21427764","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-119', 'name' => '{"name":"Šentjernej","mid":"11027458","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-208', 'name' => '{"name":"Log-Dragomer","mid":"24063470","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-87', 'name' => '{"name":"Ormož","mid":"11027172","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-173', 'name' => '{"name":"Polzela","mid":"21428035","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-22', 'name' => '{"name":"Dol pri Ljubljani","mid":"11026753","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-154', 'name' => '{"name":"Dobje","mid":"21427691","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-180', 'name' => '{"name":"Solčava","mid":"21427918","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-29', 'name' => '{"name":"Gornja Radgona","mid":"11026826","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-213', 'name' => '{"name":"Ankaran","mid":"24063526","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-159', 'name' => '{"name":"Hajdina","mid":"21427748","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-120', 'name' => '{"name":"Šentjur","mid":"11027466","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-35', 'name' => '{"name":"Hrpelje-Kozina","mid":"11027709","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-25', 'name' => '{"name":"Dravograd","mid":"11026788","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-203', 'name' => '{"name":"Straža","mid":"21433659","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-108', 'name' => '{"name":"Ruše","mid":"11027334","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-126', 'name' => '{"name":"Šoštanj","mid":"11027547","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-18', 'name' => '{"name":"Destrnik","mid":"11026702","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-110', 'name' => '{"name":"Sevnica","mid":"11027369","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-144', 'name' => '{"name":"Zreče","mid":"11027687","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-195', 'name' => '{"name":"Apače","mid":"21436437","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-169', 'name' => '{"name":"Miklavž na Dravskem polju","mid":"21428027","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-118', 'name' => '{"name":"Šentilj","mid":"11027440","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-19', 'name' => '{"name":"Divača","mid":"11026729","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
			[ 'slug' => 'SI-OB-92', 'name' => '{"name":"Podčetrtek","mid":"11027202","type":"N"}', 'spatial_unit_filter_type_id' => 3 ],
		]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('spatial_unit_filter_elements');
    }
};
